### ISSUE TITLE
prototipo 

### ISSUE THREAD

**Issue by DamGL** [SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo-damaris#2]
[Reporte de Prototipo RA.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo-damaris/files/8142984/Reporte.de.Prototipo.RA.pdf)

**Comment by CarlosSD16** [comment]
Esta completo cumple con los requerimientos 
 Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by juanpflores** [comment]
❤️ :octocat:
